sonar.projectKey=project1
sonar.projectName=NestJS App


# Adjust this based on your project structure
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.login=sqp_88acdb1c188dd6d1ce5e1e72fd487524b3604d46